name: CI Check

on:
  pull_request:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Run test style code with Laravel Pint
      - name: Run Laravel Pint (code style checker)
        run: ./vendor/bin/pint --test

      # Run PHPStan
      - name: Run PHPStan (static analysis)
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      # Run tests
      - name: Run tests
        run: php artisan test --no-interaction
